[package]
edition = "2021"
name = "strata-reth-primitives"
version = "0.1.0"

[dependencies]
alloy-sol-types = { workspace = true }
reth-primitives = { workspace = true }
serde = { workspace = true }
