[package]
edition = "2021"
name = "strata-risc0-adapter"
version = "0.1.0"

[dependencies]
anyhow.workspace = true
bincode.workspace = true
borsh.workspace = true
risc0-zkvm = "1.0.3"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
strata-primitives.workspace = true
strata-zkvm.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
default = ["prover"]
prover = []
