[package]
name = "express-proofimpl-checkpoint"
version = "0.1.0"
edition = "2021"

[dependencies]
alpen-express-primitives.workspace = true
alpen-express-state.workspace = true
anyhow.workspace = true
bitcoin.workspace = true
borsh.workspace = true
ethnum = "1.5.0"
express-proofimpl-btc-blockspace.workspace = true
express-proofimpl-l1-batch.workspace = true
express-zkvm.workspace = true
serde.workspace = true
serde_json = "1.0.127"

[dev-dependencies]
alpen-test-utils.workspace = true
rand.workspace = true
