[package]
edition = "2021"
name = "alpen-reth-evm"
version = "0.2.0-alpha.1"

[dependencies]
alpen-reth-primitives.workspace = true
strata-crypto.workspace = true
strata-primitives.workspace = true

alloy-sol-types.workspace = true
reth-primitives.workspace = true
revm.workspace = true
revm-primitives.workspace = true

[dev-dependencies]
secp256k1.workspace = true
strata-crypto = { workspace = true, features = ["rand"] }
