[toolchain]
channel = "nightly-2025-02-01"
components = [
  "cargo",
  "clippy",
  "rustc",
  "rustfmt",
  "rust-analyzer",
  "rust-docs",
  "rust-src",
  "rust-std",
  # "miri" # currently, does not support DB FFIs (results in false positives for `rockbound`)
]
