[package]
edition = "2021"
name = "risc0-guest-builder"
version = "0.1.0"

[dependencies]
express-risc0-adapter = { path = "../../crates/prover/adapters/risc0", features = [
  "prover",
], optional = true }


[dev-dependencies]
btc-blockspace = { workspace = true }
bincode = { workspace = true }
express-zkvm = { workspace = true }
zkvm-primitives = { workspace = true }
alpen-test-utils = { workspace = true }
bitcoin = { workspace = true }
express-chaintsn.workspace = true
alpen-express-state.workspace = true
alpen-express-primitives.workspace = true
borsh = { workspace = true }

[build-dependencies]
risc0-build = { version = "1.0.5" }

[package.metadata.risc0]
methods = ["guest-reth-stf", "guest-cl-stf", "btc-blockspace"]

[features]
default = []
prover = ["dep:express-risc0-adapter"]
