[package]
edition = "2021"
name = "strata-provers-perf"
version = "0.2.0-alpha.1"

[dependencies]
zkaleido.workspace = true

# proof programs
strata-proofimpl-btc-blockspace.workspace = true
strata-proofimpl-checkpoint.workspace = true
strata-proofimpl-cl-stf.workspace = true
strata-proofimpl-evm-ee-stf.workspace = true

strata-l1tx.workspace = true
strata-test-utils.workspace = true
strata-zkvm-hosts.workspace = true

# sp1
sp1-sdk = "4.1.0"
strata-sp1-guest-builder = { path = "../../provers/sp1", optional = true }
zkaleido-sp1-host = { git = "https://github.com/alpenlabs/zkaleido", tag = "v0.1.0-alpha-rc9", optional = true }

# risc0
strata-risc0-guest-builder = { path = "../../provers/risc0", optional = true }
zkaleido-risc0-host = { git = "https://github.com/alpenlabs/zkaleido", tag = "v0.1.0-alpha-rc9", optional = true }

anyhow.workspace = true
bincode.workspace = true
cfg-if.workspace = true
clap = { workspace = true, features = ["derive"] }
num-format = "0.4.4"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
time = "0.3.26"
tokio.workspace = true
tracing.workspace = true

[features]
default = ["sp1"]
sp1 = ["zkaleido-sp1-host/perf", "strata-zkvm-hosts/sp1-builder"]
risc0 = ["zkaleido-risc0-host/perf", "strata-zkvm-hosts/risc0-builder"]
