[package]
edition = "2021"
name = "strata-test-utils"
version = "0.2.0-alpha.1"

[lints]
rust.unused_crate_dependencies = "deny"

[dependencies]
strata-btcio.workspace = true
strata-chaintsn.workspace = true
strata-consensus-logic.workspace = true
strata-l1tx.workspace = true
strata-primitives.workspace = true
strata-proofimpl-evm-ee-stf.workspace = true
strata-state.workspace = true

anyhow.workspace = true
arbitrary.workspace = true
bitcoin = { workspace = true, features = ["rand-std"] }
bitcoind-async-client.workspace = true
borsh.workspace = true
hex.workspace = true
musig2.workspace = true
rand.workspace = true
rand_core.workspace = true
revm.workspace = true
serde_json.workspace = true
tokio.workspace = true
