[package]
edition = "2021"
name = "alpen-test-utils"
version = "0.1.0"

[dependencies]
alpen-express-db = { workspace = true, features = ["stubs"] }
alpen-express-primitives = { workspace = true }
alpen-express-state = { workspace = true }

anyhow = { workspace = true }
arbitrary = { workspace = true }
bitcoin = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
rockbound = { workspace = true }
