[package]
edition = "2021"
name = "alpen-vertex-rpc-api"
version = "0.1.0"

[dependencies]
alpen-vertex-primitives = { workspace = true }
alpen-vertex-state = { workspace = true }

hex = { workspace = true }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
serde = { workspace = true }
<<<<<<< HEAD
thiserror = { workspace = true }
=======
>>>>>>> c9c6402 (chore: format TOML files with taplo)
