[package]
edition = "2021"
name = "alpen-express-rpc-api"
version = "0.1.0"

[dependencies]
alpen-express-db = { workspace = true }
alpen-express-primitives = { workspace = true }
alpen-express-rpc-types = { workspace = true }
alpen-express-state = { workspace = true }
express-bridge-exec = { workspace = true }
express-bridge-txm = { workspace = true }

bitcoin = { workspace = true }
hex = { workspace = true }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
serde = { workspace = true }
serde_with = { workspace = true, features = ["hex"] }
thiserror = { workspace = true }
