[package]
edition = "2021"
name = "alpen-reth"
version = "0.2.0-alpha.1"

[[bin]]
name = "alpen-reth"
path = "src/main.rs"

[dependencies]
alpen-reth-db.workspace = true
alpen-reth-exex.workspace = true
alpen-reth-node.workspace = true
alpen-reth-rpc.workspace = true

alloy-genesis.workspace = true
alloy-rpc-types.workspace = true
async-trait.workspace = true
clap.workspace = true
eyre.workspace = true
hex.workspace = true
jsonrpsee-types.workspace = true
reqwest.workspace = true
reth.workspace = true
reth-chainspec.workspace = true
reth-cli.workspace = true
reth-cli-commands.workspace = true
reth-cli-util.workspace = true
reth-db.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
reth-rpc-eth-api.workspace = true
reth-rpc-eth-types.workspace = true
rockbound.workspace = true
serde_json.workspace = true
shellexpand = "3.0.0"
thiserror.workspace = true
tracing.workspace = true
