[package]
name = "express-proofimpl-l1-batch"
version = "0.1.0"
edition = "2021"

[dependencies]
alpen-express-primitives.workspace = true
alpen-test-utils = { workspace = true, optional = true }
anyhow.workspace = true
bitcoin.workspace = true
borsh.workspace = true
ethnum = "1.5.0"
express-proofimpl-btc-blockspace.workspace = true
serde.workspace = true
serde_json = "1.0.127"

[dev-dependencies]
rand.workspace = true
alpen-test-utils.workspace = true

[features]
test-utils = ["alpen-test-utils"]
