[package]
edition = "2021"
name = "strata-proofimpl-l1-batch"
version = "0.1.0"

[dependencies]
anyhow.workspace = true
bitcoin.workspace = true
borsh.workspace = true
ethnum.workspace = true
serde.workspace = true
serde_json = "1.0.127"
strata-primitives.workspace = true
strata-proofimpl-btc-blockspace.workspace = true
strata-state.workspace = true
strata-test-utils = { workspace = true, optional = true }

[dev-dependencies]
rand.workspace = true
strata-test-utils.workspace = true

[features]
test-utils = []
