[package]
edition = "2021"
name = "sp1-guest-builder"
version = "0.1.0"

[dependencies]
express-sp1-adapter = { path = "../../crates/prover/adapters/sp1", features = [
  "prover",
], optional = true }

[build-dependencies]
sp1-helper = "1.0.1"

[dev-dependencies]
bincode = { workspace = true }
express-zkvm = { workspace = true }
zkvm-primitives = { workspace = true }


[package.metadata.risc0]
methods = ["guest-reth-stf"]

[features]
default = []
prover = ["dep:express-sp1-adapter"]
