[package]
edition = "2021"
name = "express-sync"
version = "0.1.0"

[dependencies]
alpen-express-consensus-logic = { workspace = true }
alpen-express-db = { workspace = true }
alpen-express-primitives = { workspace = true }
alpen-express-state = { workspace = true }
alpen-express-rpc-api = { workspace = true, features = ["client"] }
alpen-express-rpc-types = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
borsh = { workspace = true }
express-storage = { workspace = true }
futures-util = { workspace = true }
indexmap = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }


[dev-dependencies]
arbitrary = { workspace = true }
