[package]
name = "alpen-vertex-evmctl"
version = "0.1.0"
edition = "2021"

[dependencies]
alpen-vertex-primitives = { workspace = true }
alpen-vertex-state = { workspace = true }

thiserror = { workspace = true }