[package]
edition = "2021"
name = "alpen-express-evmctl"
version = "0.1.0"

[dependencies]
alpen-express-primitives = { workspace = true }
alpen-express-state = { workspace = true }

thiserror = { workspace = true }
