[package]
edition = "2021"
name = "strata-reth-node"
version = "0.1.0"

[dependencies]
strata-reth-evm.workspace = true
strata-reth-primitives.workspace = true
strata-reth-rpc.workspace = true

alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-rpc-types.workspace = true
eyre.workspace = true
reth.workspace = true
reth-basic-payload-builder.workspace = true
reth-chain-state.workspace = true
reth-chainspec.workspace = true
reth-db.workspace = true
reth-errors.workspace = true
reth-ethereum-payload-builder.workspace = true
reth-evm.workspace = true
reth-evm-ethereum.workspace = true
reth-node-api.workspace = true
reth-node-builder.workspace = true
reth-node-ethereum.workspace = true
reth-payload-builder.workspace = true
reth-payload-validator.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
reth-transaction-pool.workspace = true
reth-trie.workspace = true
reth-trie-common.workspace = true
reth-trie-db.workspace = true
revm.workspace = true
revm-primitives.workspace = true
serde.workspace = true
tracing.workspace = true
