[package]
edition = "2021"
name = "alpen-reth-exex"
version = "0.3.0-alpha.1"

[dependencies]
alpen-reth-db.workspace = true
alpen-reth-node.workspace = true
strata-proofimpl-evm-ee-stf.workspace = true

alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-rpc-types.workspace = true
anyhow.workspace = true
bincode.workspace = true
eyre.workspace = true
futures-util.workspace = true
reth-evm.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
reth-revm.workspace = true
reth-rpc-types-compat.workspace = true
reth-trie.workspace = true
reth-trie-common.workspace = true
revm-primitives.workspace = true
rockbound.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
serde.workspace = true
tempfile.workspace = true
