[package]
edition = "2021"
name = "alpen-express-rpc-types"
version = "0.1.0"

[dependencies]
alpen-express-db = { workspace = true }
alpen-express-state = { workspace = true }

bitcoin = { workspace = true }
hex = { workspace = true }
jsonrpsee = { workspace = true, features = ["server"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
