[package]
edition = "2021"
name = "alpen-express-rpc-types"
version = "0.1.0"

[dependencies]
bitcoin = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
