[package]
edition = "2021"
name = "guest-risc0-evm-ee-stf"
version = "0.1.0"

[workspace]

[dependencies]
strata-proofimpl-evm-ee-stf = { path = "../../../crates/proof-impl/evm-ee-stf" }
zkaleido-risc0-guest-env = { git = "https://github.com/alpenlabs/zkaleido", tag = "v0.1.0-alpha-rc10" }
