[package]
edition = "2021"
name = "guest-risc0-evm-ee-stf"
version = "0.1.0"

[workspace]

[dependencies]
strata-proofimpl-evm-ee-stf = { path = "../../../crates/proof-impl/evm-ee-stf" }
zkaleido-risc0-adapter = { path = "../../../crates/zkvm/adapters/risc0" }
