[package]
edition = "2021"
name = "alpen-reth-rpc"
version = "0.1.0"

[dependencies]
alpen-reth-db.workspace = true
alpen-reth-statediff.workspace = true
strata-proofimpl-evm-ee-stf.workspace = true
strata-rpc-utils.workspace = true

alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-types-eth.workspace = true
bincode.workspace = true
eyre.workspace = true
hex.workspace = true
jsonrpsee = { workspace = true, features = ["server", "macros"] }
jsonrpsee-types.workspace = true
parking_lot.workspace = true
reqwest.workspace = true
reth-chainspec.workspace = true
reth-ethereum-forks.workspace = true
reth-evm.workspace = true
reth-network-api.workspace = true
reth-node-api.workspace = true
reth-node-builder.workspace = true
reth-primitives.workspace = true
reth-primitives-traits.workspace = true
reth-provider.workspace = true
reth-revm.workspace = true
reth-rpc.workspace = true
reth-rpc-eth-api.workspace = true
reth-rpc-eth-types.workspace = true
reth-rpc-server-types.workspace = true
reth-tasks = { workspace = true, features = ["rayon"] }
reth-transaction-pool.workspace = true
revm.workspace = true
revm-primitives.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "sync"] }
tracing.workspace = true
