[package]
name = "alpen-vertex-evmexec"
version = "0.1.0"
edition = "2021"

[dependencies]
alpen-vertex-evmctl = { workspace = true }
alpen-vertex-primitives = { workspace = true }
alpen-vertex-state = { workspace = true }
arbitrary = { workspace = true }
borsh = { workspace = true }
futures = { workspace = true }
jsonrpsee = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
reth-primitives = { workspace = true }
reth-node-ethereum = { workspace = true }
reth-rpc = { workspace = true }
reth-rpc-api = { workspace = true }
reth-rpc-layer = { workspace = true }
reth-rpc-types = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
rand = { workspace = true }
