[package]
edition = "2021"
name = "strata-proofimpl-cl-stf"
version = "0.1.0"

[dependencies]
strata-chaintsn.workspace = true
strata-crypto.workspace = true
strata-primitives.workspace = true
strata-proofimpl-evm-ee-stf.workspace = true
strata-state.workspace = true
strata-zkvm.workspace = true

borsh.workspace = true

[dev-dependencies]
strata-test-utils.workspace = true
