[package]
edition = "2021"
name = "guest-cl-stf"
version = "0.1.0"

[workspace]

[dependencies]
alpen-express-primitives = { path = "../../../crates/primitives" }
bitcoin = { version = "0.32.1", features = ["serde"] }
borsh = { version = "1.5.0", features = ["derive"] }
express-cl-stf = { path = "../../../crates/prover/cl-stf" }
sp1-zkvm = "1.0.1"


[patch.crates-io]
secp256k1 = { git = "https://github.com/sp1-patches/rust-secp256k1", branch = "patch-secp256k1-v0.29.0-old" }
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.10.8" }
