[package]
description = "Definition of supported chainspecs."
edition = "2021"
name = "alpen-chainspec"
version = "0.1.0"

[dependencies]
alloy-genesis.workspace = true
eyre.workspace = true
reth-chainspec.workspace = true
reth-cli.workspace = true
serde_json.workspace = true
shellexpand = "3.0.0"
