[package]
edition = "2021"
name = "strata-proofimpl-evm-ee-stf"
version = "0.1.0"

[dependencies]
strata-primitives.workspace = true
strata-reth-evm.workspace = true
strata-reth-primitives.workspace = true
strata-state.workspace = true
strata-zkvm.workspace = true

alloy-consensus = { workspace = true, features = ["serde-bincode-compat"] }
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-rlp-derive.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-types-eth.workspace = true
anyhow.workspace = true
k256 = { version = "=0.13.3", features = [
  "std",
  "ecdsa",
], default-features = false }
reth-primitives.workspace = true
reth-trie-common.workspace = true
revm.workspace = true
rlp = "0.5.2"
serde.workspace = true
serde_with.workspace = true
thiserror = "1.0"


[dev-dependencies]
bincode.workspace = true
hex-literal = "0.4"
serde_json.workspace = true
