[package]
edition = "2021"
name = "strata-proofimpl-evm-ee-stf"
version = "0.1.0"

[dependencies]
alloy-eips = { version = "0.2", default-features = false }
alloy-rlp = { version = "0.3.4", default-features = false }
alloy-rlp-derive = { version = "0.3", default-features = false }
alloy-rpc-types = { workspace = true, default-features = false, features = [
  "eth",
] }
anyhow.workspace = true
k256 = { version = "=0.13.3", features = [
  "std",
  "ecdsa",
], default-features = false }
reth-primitives = { workspace = true, default-features = false }
reth-trie-common.workspace = true
revm.workspace = true
rlp = "0.5.2"
serde.workspace = true
strata-reth-evm.workspace = true
strata-reth-primitives.workspace = true
thiserror = "1.0"

[dev-dependencies]
bincode.workspace = true
hex-literal = "0.4"
serde_json.workspace = true
