[package]
edition = "2021"
name = "alpen-cli"
version = "0.3.0-alpha.1"

[[bin]]
name = "alpen"
path = "src/main.rs"

[dependencies]
strata-primitives.workspace = true

aes-gcm-siv = "0.11.1"
alloy = { version = "0.3.5", features = [
  "std",
  "rpc-client-ws",
  "network",
  "signers",
  "signer-local",
  "providers",
  "rpc-types",
] }
argh.workspace = true
argon2 = "0.5.3"
async-trait.workspace = true
bdk_bitcoind_rpc.workspace = true
bdk_esplora.workspace = true
bdk_wallet = { workspace = true, features = ["rusqlite"] }
bip39 = { version = "2.0.0", features = ["all-languages"] }
chrono.workspace = true
colored = "2.2.0"
config = { version = "0.14.0", default-features = false, features = ["toml"] }
dialoguer = "0.11.0"
directories = "5.0.1"
indicatif = { version = "0.17.8", features = ["improved_unicode", "tokio"] }
make_buf = { git = "https://github.com/alpenlabs/make_buf.git", rev = "903dbe1d4068712ee046c54fe2906ba04e72c905" }
rand_core.workspace = true
reqwest.workspace = true
serde.workspace = true
sha2 = { version = "0.10.8", features = ["loongarch64_asm"] }
shrex.workspace = true
sled = "0.34.7"
terrors.workspace = true
tokio.workspace = true
zeroize.workspace = true
zxcvbn = "3.1.0"

# sha2 fails to compile on windows with the "asm" feature
[target.'cfg(not(target_os = "windows"))'.dependencies]
sha2 = { version = "0.10.8", features = ["asm", "loongarch64_asm"] }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
keyring = { version = "3.3.0", default-features = false, features = [
  "apple-native",
] }

[target.'cfg(target_os = "windows")'.dependencies]
keyring = { version = "3.3.0", default-features = false, features = [
  "windows-native",
] }

[dev-dependencies]
toml = "0.8.20"