[package]
edition = "2021"
name = "guest-risc0-cl-stf"
version = "0.1.0"

[workspace]

[dependencies]
strata-proofimpl-cl-stf = { path = "../../../crates/proof-impl/cl-stf" }
zkaleido-risc0-adapter = { git = "https://github.com/alpenlabs/zkaleido", tag = "v0.1.0-alpha-rc1" }
