[package]
edition = "2021"
name = "strata-tasks"
version = "0.3.0-alpha.1"

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
arbitrary.workspace = true
