[package]
edition = "2021"
name = "strata-proofimpl-btc-blockspace"
version = "0.1.0"

[dependencies]
bitcoin = { workspace = true, features = ["serde"] }
borsh.workspace = true
serde = { workspace = true, features = ["derive"] }
sha2.workspace = true
strata-bridge-tx-builder.workspace = true
strata-primitives.workspace = true
strata-state.workspace = true
strata-tx-parser.workspace = true
strata-zkvm.workspace = true

[dev-dependencies]
hex.workspace = true
rand.workspace = true
strata-test-utils.workspace = true
strata-native-zkvm-adapter.workspace = true
