[package]
edition = "2021"
name = "strata-status"
version = "0.1.0"

[dependencies]
strata-primitives.workspace = true
strata-rpc-types.workspace = true
strata-state.workspace = true

arbitrary.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
