# Runs `cargo update` periodically.

name: Update Dependencies

on:
  schedule:
    # Run at the first of every month
    - cron: "0 0 1 * *"
  workflow_dispatch: # Needed so we can run it manually

env:
  AUTHOR: Update Cargo.lock Bot <no-reply@alpenlabs.io>
  BRANCH: create-pull-request/automated-cargo-update
  TITLE: "chore(deps): monthly `cargo update`"
  BODY: |
    Automation to keep dependencies in `Cargo.lock` current.

    <details><summary><strong>cargo update log</strong></summary>
    <p>

    ```log
    $cargo_update_log
    ```

    </p>
    </details>

permissions: {}

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create commits
      pull-requests: write # Needed to create a PR
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@a02741459ec5e501b9843ed30b535ca0a0376ae4 # nightly
        with:
          toolchain: nightly-2024-07-27

      - name: cargo update
        # Remove first line that always just says "Updating crates.io index"
        run: cargo update --color never 2>&1 | sed '/crates.io index/d' | tee -a cargo_update.log

      - name: craft commit message and PR body
        id: msg
        run: |
          cargo_update_log="$(cat cargo_update.log)"
          export cargo_update_log

          {
            echo "commit_message<<EOF"
            echo "$TITLE"
            echo ""
            echo "$cargo_update_log"
            echo ""
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

          {
            echo "body<<EOF"
            echo "$BODY" | envsubst
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          add-paths: ./Cargo.lock
          commit-message: ${{ steps.msg.outputs.commit_message }}
          author: ${{ env.AUTHOR }}
          title: ${{ env.TITLE }}
          body: ${{ steps.msg.outputs.body }}
          branch: ${{ env.BRANCH }}
